import { useState, useEffect } from 'react'
import Groq from 'groq-sdk'

const groq = new Groq({
  apiKey: import.meta.env.VITE_GROQ_API_KEY,
  dangerouslyAllowBrowser: true,
})

function App() {
  const [name, setName] = useState('')
  const [hobby, setHobby] = useState('')
  const [roast, setRoast] = useState('')
  const [loading, setLoading] = useState(false)
  const [darkMode, setDarkMode] = useState(() => {
    return localStorage.getItem('darkMode') === 'true'
  })
  const [copied, setCopied] = useState(false)

  useEffect(() => {
    localStorage.setItem('darkMode', darkMode)
  }, [darkMode])

  const generateRoast = async (e) => {
    e.preventDefault()
    if (!name.trim() || !hobby.trim()) return

    setLoading(true)
    setRoast('')

    try {
      const chatCompletion = await groq.chat.completions.create({
        messages: [
          {
            role: 'system',
            content:
              'You are a savage roast comedian. Given a person\'s name and hobby, generate a short, funny, brutal (but not mean-spirited) roast in 2-3 sentences. Keep it witty and entertaining. Use their name and hobby creatively.',
          },
          {
            role: 'user',
            content: `Roast me! My name is ${name.trim()} and my hobby is ${hobby.trim()}.`,
          },
        ],
        model: 'llama-3.3-70b-versatile',
        temperature: 0.9,
        max_tokens: 256,
      })

      setRoast(chatCompletion.choices[0]?.message?.content || 'Even AI refuses to roast you. That\'s how boring you are.')
    } catch (error) {
      console.error('Groq API error:', error)
      setRoast('Oops! The roast machine broke. Maybe you\'re just too unroastable... or check your API key.')
    } finally {
      setLoading(false)
    }
  }

  const handleCopy = async () => {
    if (!roast) return
    try {
      await navigator.clipboard.writeText(roast)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      const textarea = document.createElement('textarea')
      textarea.value = roast
      document.body.appendChild(textarea)
      textarea.select()
      document.execCommand('copy')
      document.body.removeChild(textarea)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    }
  }

  const handleShare = async () => {
    if (!roast) return
    const shareText = `🔥 AI Roast for ${name}:\n\n"${roast}"\n\n— Generated by AI Roast Me`

    if (navigator.share) {
      try {
        await navigator.share({ title: 'AI Roast Me', text: shareText })
      } catch {
        // User cancelled share
      }
    } else {
      await navigator.clipboard.writeText(shareText)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    }
  }

  return (
    <div className={`min-h-screen transition-colors duration-300 ${darkMode ? 'bg-gray-950 text-white' : 'bg-orange-50 text-gray-900'}`}>
      {/* Dark Mode Toggle */}
      <div className="absolute top-4 right-4">
        <button
          onClick={() => setDarkMode(!darkMode)}
          className={`p-3 rounded-full transition-all duration-300 cursor-pointer ${
            darkMode
              ? 'bg-gray-800 hover:bg-gray-700 text-yellow-400'
              : 'bg-white hover:bg-gray-100 text-gray-700 shadow-md'
          }`}
          aria-label="Toggle dark mode"
        >
          {darkMode ? (
            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
              <path fillRule="evenodd" d="M10 2a1 1 0 011 1v1a1 1 0 11-2 0V3a1 1 0 011-1zm4 8a4 4 0 11-8 0 4 4 0 018 0zm-.464 4.95l.707.707a1 1 0 001.414-1.414l-.707-.707a1 1 0 00-1.414 1.414zm2.12-10.607a1 1 0 010 1.414l-.706.707a1 1 0 11-1.414-1.414l.707-.707a1 1 0 011.414 0zM17 11a1 1 0 100-2h-1a1 1 0 100 2h1zm-7 4a1 1 0 011 1v1a1 1 0 11-2 0v-1a1 1 0 011-1zM5.05 6.464A1 1 0 106.465 5.05l-.708-.707a1 1 0 00-1.414 1.414l.707.707zm1.414 8.486l-.707.707a1 1 0 01-1.414-1.414l.707-.707a1 1 0 011.414 1.414zM4 11a1 1 0 100-2H3a1 1 0 000 2h1z" clipRule="evenodd" />
            </svg>
          ) : (
            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
              <path d="M17.293 13.293A8 8 0 016.707 2.707a8.001 8.001 0 1010.586 10.586z" />
            </svg>
          )}
        </button>
      </div>

      <div className="max-w-xl mx-auto px-4 py-16">
        {/* Header */}
        <div className="text-center mb-10">
          <h1 className="text-5xl font-extrabold mb-2 tracking-tight">
            <span className="inline-block mr-2">🔥</span>
            <span className="bg-gradient-to-r from-orange-500 via-red-500 to-pink-500 bg-clip-text text-transparent">
              AI Roast Me
            </span>
          </h1>
          <p className={`text-lg ${darkMode ? 'text-gray-400' : 'text-gray-600'}`}>
            Enter your name & hobby. Get brutally roasted by AI.
          </p>
        </div>

        {/* Form */}
        <form onSubmit={generateRoast} className="space-y-4 mb-8">
          <div>
            <input
              type="text"
              placeholder="Your name..."
              value={name}
              onChange={(e) => setName(e.target.value)}
              className={`w-full px-4 py-3 rounded-xl border-2 text-lg outline-none transition-all duration-200 ${
                darkMode
                  ? 'bg-gray-900 border-gray-700 text-white placeholder-gray-500 focus:border-orange-500'
                  : 'bg-white border-gray-200 text-gray-900 placeholder-gray-400 focus:border-orange-400'
              }`}
            />
          </div>
          <div>
            <input
              type="text"
              placeholder="Your hobby..."
              value={hobby}
              onChange={(e) => setHobby(e.target.value)}
              className={`w-full px-4 py-3 rounded-xl border-2 text-lg outline-none transition-all duration-200 ${
                darkMode
                  ? 'bg-gray-900 border-gray-700 text-white placeholder-gray-500 focus:border-orange-500'
                  : 'bg-white border-gray-200 text-gray-900 placeholder-gray-400 focus:border-orange-400'
              }`}
            />
          </div>
          <button
            type="submit"
            disabled={loading || !name.trim() || !hobby.trim()}
            className="w-full py-3 rounded-xl text-lg font-bold text-white bg-gradient-to-r from-orange-500 via-red-500 to-pink-500 hover:from-orange-600 hover:via-red-600 hover:to-pink-600 transition-all duration-200 disabled:opacity-50 disabled:cursor-not-allowed cursor-pointer shadow-lg hover:shadow-xl active:scale-[0.98]"
          >
            {loading ? (
              <span className="inline-flex items-center gap-2">
                <svg className="animate-spin h-5 w-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                </svg>
                Roasting...
              </span>
            ) : (
              '🔥 Roast Me!'
            )}
          </button>
        </form>

        {/* Roast Card */}
        {roast && (
          <div
            className={`rounded-2xl p-6 shadow-2xl animate-fade-in ${
              darkMode
                ? 'bg-gradient-to-br from-gray-900 via-gray-800 to-gray-900 border border-gray-700'
                : 'bg-white border border-gray-100'
            }`}
            style={{
              animation: 'fadeInUp 0.5s ease-out',
            }}
          >
            <div className="flex items-start gap-3 mb-4">
              <span className="text-3xl">🎤</span>
              <div>
                <h3 className={`font-bold text-lg ${darkMode ? 'text-orange-400' : 'text-orange-600'}`}>
                  Roast for {name}
                </h3>
                <p className={`text-sm ${darkMode ? 'text-gray-500' : 'text-gray-400'}`}>
                  Hobby: {hobby}
                </p>
              </div>
            </div>

            <p className={`text-lg leading-relaxed mb-6 ${darkMode ? 'text-gray-200' : 'text-gray-700'}`}>
              "{roast}"
            </p>

            {/* Action Buttons */}
            <div className="flex gap-3">
              <button
                onClick={handleCopy}
                className={`flex-1 flex items-center justify-center gap-2 py-2.5 rounded-xl font-medium transition-all duration-200 cursor-pointer ${
                  darkMode
                    ? 'bg-gray-700 hover:bg-gray-600 text-gray-200'
                    : 'bg-gray-100 hover:bg-gray-200 text-gray-700'
                }`}
              >
                {copied ? (
                  <>
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 text-green-500" viewBox="0 0 20 20" fill="currentColor">
                      <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                    </svg>
                    Copied!
                  </>
                ) : (
                  <>
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" viewBox="0 0 20 20" fill="currentColor">
                      <path d="M8 3a1 1 0 011-1h2a1 1 0 110 2H9a1 1 0 01-1-1z" />
                      <path d="M6 3a2 2 0 00-2 2v11a2 2 0 002 2h8a2 2 0 002-2V5a2 2 0 00-2-2 3 3 0 01-3 3H9a3 3 0 01-3-3z" />
                    </svg>
                    Copy
                  </>
                )}
              </button>

              <button
                onClick={handleShare}
                className={`flex-1 flex items-center justify-center gap-2 py-2.5 rounded-xl font-medium transition-all duration-200 cursor-pointer ${
                  darkMode
                    ? 'bg-gray-700 hover:bg-gray-600 text-gray-200'
                    : 'bg-gray-100 hover:bg-gray-200 text-gray-700'
                }`}
              >
                <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" viewBox="0 0 20 20" fill="currentColor">
                  <path d="M15 8a3 3 0 10-2.977-2.63l-4.94 2.47a3 3 0 100 4.319l4.94 2.47a3 3 0 10.895-1.789l-4.94-2.47a3.027 3.027 0 000-.74l4.94-2.47C13.456 7.68 14.19 8 15 8z" />
                </svg>
                Share
              </button>

              <button
                onClick={() => { setRoast(''); setName(''); setHobby('') }}
                className="flex-1 flex items-center justify-center gap-2 py-2.5 rounded-xl font-medium bg-gradient-to-r from-orange-500 to-red-500 text-white hover:from-orange-600 hover:to-red-600 transition-all duration-200 cursor-pointer"
              >
                🔄 Again
              </button>
            </div>
          </div>
        )}

        {/* Footer */}
        <p className={`text-center text-sm mt-12 ${darkMode ? 'text-gray-600' : 'text-gray-400'}`}>
          Powered by Groq + Llama 3.3 &middot; All roasts are AI-generated comedy
        </p>
      </div>

      {/* Animation keyframes */}
      <style>{`
        @keyframes fadeInUp {
          from {
            opacity: 0;
            transform: translateY(20px);
          }
          to {
            opacity: 1;
            transform: translateY(0);
          }
        }
      `}</style>
    </div>
  )
}

export default App
